[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `$SHELL`
# with whatever you want started, such as `sway`.
command = "agreety --cmd $SHELL"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "m4n4pe"

[initial_session]
command = "sway-run"
user = "m4n4pe"

# NOTE ONE LAST CHANGE: "sway-run" instead of "sway", along with a new file /usr/local/bin/sway-run (must be made executable)
