lisgd -v \
-g "1,DU,B,*,R,/usr/local/bin/kbd_show.sh" \
-g "1,UD,B,*,R,/usr/local/bin/kbd_hide.sh" \
-g "1,UD,T,*,R,/usr/local/bin/waybar_toggle.sh" \
-g "1,DU,T,*,R,/usr/local/bin/waybar_toggle.sh" \
-g "1,LR,L,*,R,/usr/local/bin/lavalauncher_show.sh" \
-g "1,RL,L,*,R,/usr/local/bin/lavalauncher_kill.sh" \
-g "2,DU,B,*,R,/usr/local/bin/sov_show.sh" \
-g "2,UD,B,*,R,/usr/local/bin/sov_hide.sh" \
-g "2,RL,N,*,R,swaymsg workspace next" \
-g "2,LR,N,*,R,swaymsg workspace prev"
